# Generated by Django 4.0.3 on 2023-05-30 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_category_comment_product_remove_question_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcount',
            old_name='question',
            new_name='product',
        ),
    ]
