# Generated by Django 4.0.3 on 2023-05-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_question_productcount_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Product',
            new_name='product',
        ),
    ]
