# Generated by Django 4.0.3 on 2023-06-17 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0004_rename_product_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='voter',
            field=models.ManyToManyField(related_name='liked_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
