# Generated by Django 4.0.3 on 2023-06-17 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_alter_product_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='voter',
            field=models.ManyToManyField(related_name='liked_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
